# Generated by Django 3.2.12 on 2022-05-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=255)),
                ('item_due_month', models.IntegerField()),
                ('item_due_day', models.IntegerField()),
            ],
        ),
    ]
