# Generated by Django 3.2.12 on 2022-05-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_due_day',
            new_name='due_day',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_due_month',
            new_name='due_month',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_text',
            new_name='text',
        ),
    ]
